config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

Rails.application.routes.draw do

  resources :articles
  resources :rectangles
  resources :patients

  root 'welcome#index'
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/exam.rb
class Exam < ActiveRecord::Base
end

app/models/medication.rb
class Medication < ActiveRecord::Base
end

app/models/patient.rb
class Patient < ActiveRecord::Base
end

app/models/rectangle.rb
class Rectangle < ActiveRecord::Base
  validates :width,:height, presence:true,
                            numericality: {
                              only_integer: true,
                              less_than_or_equal_to:700,
                              greater_than_or_equal_to:1
                            }
  validates :name, presence:true
end

app/models/visit.rb
class Visit < ActiveRecord::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
def index
  @articles = Article.all
end

def show
  @article = Article.find(params[:id])
end

def new
end

def create
  @article = Article.new(article_params)

  @article.save
  redirect_to @article
end

private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  def index
      @exams = Exam.all
    end

  def show
    @exam = Exam.find(params[:id])
  end

  def new
  end

  def create
    @exam = Exam.new(visitt_params)

    @exam.save
    redirect_to @exam
  end

  private
  def exam_params
    params.require(:exam).permit(:id_nim, :examtype, :examdate, :status, :comments)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
      @patients = Patient.all
    end

  def show
    @patient = Patient.find(params[:id])
    @medication = Medication.find_by name: 'Alex Sweeten'
    #  @medication = Medication.find(params[:id]) # show * where Medication.Name = Patient.Name Post.find_by name: 'Spartacus', rating: 4
  end

  def new
  end

  def create
    @patient = Patient.new(patient_params)

    @patient.save
    redirect_to @patient
  end

  private
  def patient_params
    params.require(:patient).permit(:name, :phone, :address, :dateofbirth, :status, :medication, :emergencycontact)
  end
end

app/controllers/rectangles_controller.rb
class RectanglesController < ApplicationController

  def index
    @rectangles = Rectangle.all
  end

  def show
  @rectangle = Rectangle.find(params[:id])
end

  def new
    @rectangle = Rectangle.new
  end

  def edit
    @rectangle = Rectangle.find(params[:id])
  end

  def create
    @rectangle = Rectangle.new(rectangle_params)

    if @rectangle.save
    redirect_to @rectangle
  else
    render 'new'
  end
end

  def update
    @rectangle = Rectangle.find(params[:id])

  if @rectangle.update(rectangle_params)
    redirect_to @rectangle
  else
    render 'edit'
  end
end

def destroy
  @rectangle = Rectangle.find(params[:id])
  @rectangle.destroy

  redirect_to rectangles_path
end

private
def rectangle_params
  params.require(:rectangle).permit(:width, :height, :color, :name, :images)

end

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def index
      @visits = Visit.all
    end

  def show
    @visit = Visit.find(params[:id])
  end

  def new
  end

  def create
    @visit = Visit.new(visitt_params)

    @visit.save
    redirect_to @visit
  end

  private
  def visit_params
    params.require(:visit).permit(:id_num, :practitioner_name, :specialty, :dateofvisit, :comments)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/patient_helper.rb
module PatientHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/rectangle_helper.rb
module RectangleHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1>Listing articles</h1>


<table>
  <tr>
    <th>Width:</th>
    <th>Height:</th>
    <th>Colour:</th>

  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Back', articles_path %>

app/views/exams/new.html.erb
<h1>Test</h1>

app/views/rectangles/edit.html.erb
<div id="nav_bar">
<div class="nav_bar_content">
<a class="nav_bar_link"><%= link_to 'Home', controller: 'welcome' %></a>
<a class="nav_bar_link"><%= link_to 'Display', controller: 'rectangles' %></a>
<a class="nav_bar_link"><%= link_to 'Add', new_rectangle_path %></a>
</div>
</div>
<body>
<h1>Editing Rectangles</h1>

<%= form_for :rectangle, url: rectangle_path(@rectangle), method: :patch do |f| %>

  <% if @rectangle.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@rectangle.errors.count, "error") %> prohibited
        this rectangle from being saved:
      </h2>
      <ul>
        <% @rectangle.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :width %>:   (Enter an integer between 1 and 700)<br>
    <%= f.text_area :width %>
  </p>

  <p>
    <%= f.label :height %>:   (Enter an integer between 1 and 700)<br>
    <%= f.text_area :height %>
  </p>

  <p>
    <%= f.label :color %><br>
    <%= f.select(:color,
    options_for_select([['Black', 'Black'],
    ['Blue', 'Blue'],
    ['Brown', 'Brown'],
    ['Gray', 'Gray'],
    ['Green', 'Green'],
    ['Orange', 'Orange'],
    ['Pink', 'Pink'],
    ['Purple', 'Purple'],
    ['Red', 'Red'],
    ['White', 'White'],
    ['Yellow', 'Yellow']])) %>
  </p>

  <p>
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </p>

  <p>
    <%= f.label :images %><br>
    <%= f.select(:images,
    options_for_select([['NoImage', 'NoImage'],
    ['GangnamStyle', 'GangnamStyle'],
    ['GGDanny', 'GGDanny'],
    ['Pepsi', 'Pepsi'],
    ['Pikachu', 'Pikachu'],
    ['Space', 'Space'],
    ['Spooky', 'Spooky']])) %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', rectangles_path %>
</body>

app/views/rectangles/index.html.erb
<body>
  <div id="nav_bar">
  <div class="nav_bar_content">
  <a class="nav_bar_link"><%= link_to 'Home', controller: 'welcome' %></a>
  Display
  <a class="nav_bar_link"><%= link_to 'Add', new_rectangle_path%></a>
  </div>
  </div>
<h1>Rectangle Database</h1>
<h3><%= link_to 'Click here to add a Rectangle!', new_rectangle_path %></h3>

<div id="database_table">
<table id="rectangle_table">
  <tr>
    <th>Width</th>
    <th>Height</th>
    <th>Color</th>
    <th>Image</th>
    <th>Owner</th>
    <th>Controls</th>

  </tr>

  <% @rectangles.each do |rectangle| %>

    <tr>
      <td><%= rectangle.width %>px.</td>
      <td><%= rectangle.height %>px.</td>
      <td><%= rectangle.color %></td>
      <td><%= rectangle.images %></td>
      <td><%= rectangle.name %></td>
      <td id="special"><%= link_to 'Edit', edit_rectangle_path(rectangle) %>
          <%= link_to 'Delete', rectangle_path(rectangle),
              method: :delete,
              data: { confirm: 'Are you sure you want to delete this rectangle? You might make it sad ;(' } %></td>
      <td id="special"></td>


    </tr>
  <% end %>
</table>
</div>

<h2> Display </h2>
<div id="display">

<% @rectangles.each do |rectangle| %>
  <div id="shell">

  This is <%= rectangle.name%>'s Rectangle

  <div id="element" style="width:<%= rectangle.width %>px;
    height:<%= rectangle.height %>px;
    background:<%= rectangle.color %>">

<% if rectangle.images!="NoImage" %>
     <img src="/assets/<%= rectangle.images%>.gif" />
<% end %>

  </div>
</div>
  <% end %>
</div>
</body>

app/views/rectangles/new.html.erb
<body>
<div id="nav_bar">
<div class="nav_bar_content">
<a class="nav_bar_link"><%= link_to 'Home', controller: 'welcome' %></a>
<a class="nav_bar_link"><%= link_to 'Display', controller: 'rectangles' %></a>
Add
</div>
</div><h1>New Rectangle</h1>

<%= form_for :rectangle, url: rectangles_path do |f| %>

<% if @rectangle.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@rectangle.errors.count, "error") %> prohibited
        this rectangle from being saved:
      </h2>
      <ul>
        <% @rectangle.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :width %>:   (Enter an integer between 1 and 700)<br>
    <%= f.text_area :width %>
  </p>

  <p>
    <%= f.label :height %>:   (Enter an integer between 1 and 700)<br>
    <%= f.text_area :height %>
  </p>

  <p>
    <%= f.label :color %><br>
    <%= f.select(:color,
    options_for_select([['Black', 'Black'],
    ['Blue', 'Blue'],
    ['Brown', 'Brown'],
    ['Gray', 'Gray'],
    ['Green', 'Green'],
    ['Orange', 'Orange'],
    ['Pink', 'Pink'],
    ['Purple', 'Purple'],
    ['Red', 'Red'],
    ['White', 'White'],
    ['Yellow', 'Yellow']])) %>
  </p>

  <p>
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </p>

  <p>
    <%= f.label :images %><br>
    <%= f.select(:images,
    options_for_select([['NoImage', 'NoImage'],
    ['GangnamStyle', 'GangnamStyle'],
    ['GGDanny', 'GGDanny'],
    ['Pepsi', 'Pepsi'],
    ['Pikachu', 'Pikachu'],
    ['Space', 'Space'],
    ['Spooky', 'Spooky']])) %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', rectangles_path %>
</body>

app/views/rectangles/show.html.erb
<body>
<div id="nav_bar">
<div class="nav_bar_content">
<a class="nav_bar_link"><%= link_to 'Home', controller: 'welcome' %></a>
Display
<a class="nav_bar_link"><%= link_to 'Add', new_rectangle_path%></a>
</div>
</div>

<p>
  <strong>Width:</strong>
  <%= @rectangle.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @rectangle.height %>
</p>

<p>
  <strong>Color:</strong>
  <%= @rectangle.color %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @rectangle.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @rectangle.images %>
</p>


<h3><%= link_to 'Thank you! Click here to go back to Display', rectangles_path %></h3>
</body>

app/views/visits/new.html.erb
<h1> EY YO BOI </h1>