config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

Rails.application.routes.draw do

  resources :articles
  resources :rectangles
  resources :patients

  root 'welcome#index'
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/exam.rb
class Exam < ActiveRecord::Base
end

app/models/medication.rb
class Medication < ActiveRecord::Base
end

app/models/patient.rb
class Patient < ActiveRecord::Base
end

app/models/rectangle.rb
class Rectangle < ActiveRecord::Base
  validates :width,:height, presence:true,
                            numericality: {
                              only_integer: true,
                              less_than_or_equal_to:700,
                              greater_than_or_equal_to:1
                            }
  validates :name, presence:true
end

app/models/visit.rb
class Visit < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
def index
  @articles = Article.all
end

def show
  @article = Article.find(params[:id])
end

def new
end

def create
  @article = Article.new(article_params)

  @article.save
  redirect_to @article
end

private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  def index
      @exams = Exam.all
    end

  def show
    @exam = Exam.find(params[:id])
  end

  def new
  end

  def create
    @exam = Exam.new(visitt_params)

    @exam.save
    redirect_to @exam
  end

  private
  def exam_params
    params.require(:exam).permit(:id_nim, :examtype, :examdate, :status, :comments)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
      @patients = Patient.all
    end

  def show
    @patient = Patient.find(params[:id])
    @medication = Medication.find_by name: 'Alex Sweeten'
    #  @medication = Medication.find(params[:id]) # show * where Medication.Name = Patient.Name Post.find_by name: 'Spartacus', rating: 4
  end

  def new
  end

  def create
    @patient = Patient.new(patient_params)

    @patient.save
    redirect_to @patient
  end

  private
  def patient_params
    params.require(:patient).permit(:name, :phone, :address, :dateofbirth, :status, :medication, :emergencycontact)
  end
end

app/controllers/rectangles_controller.rb
class RectanglesController < ApplicationController

  def index
    @rectangles = Rectangle.all
  end

  def show
  @rectangle = Rectangle.find(params[:id])
end

  def new
    @rectangle = Rectangle.new
  end

  def edit
    @rectangle = Rectangle.find(params[:id])
  end

  def create
    @rectangle = Rectangle.new(rectangle_params)

    if @rectangle.save
    redirect_to @rectangle
  else
    render 'new'
  end
end

  def update
    @rectangle = Rectangle.find(params[:id])

  if @rectangle.update(rectangle_params)
    redirect_to @rectangle
  else
    render 'edit'
  end
end

def destroy
  @rectangle = Rectangle.find(params[:id])
  @rectangle.destroy

  redirect_to rectangles_path
end

private
def rectangle_params
  params.require(:rectangle).permit(:width, :height, :color, :name, :images)

end

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def index
      @visits = Visit.all
    end

  def show
    @visit = Visit.find(params[:id])
  end

  def new
  end

  def create
    @visit = Visit.new(visitt_params)

    @visit.save
    redirect_to @visit
  end

  private
  def visit_params
    params.require(:visit).permit(:id_num, :practitioner_name, :specialty, :dateofvisit, :comments)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/patient_helper.rb
module PatientHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/rectangle_helper.rb
module RectangleHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/patients/index.html.erb
<h1>Listing patients</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @patients.each do |patient| %>
    <tr>
      <td><%= patient.name %></td>
    </tr>
    <tr>
      <td><%= patient.status %></td>
    </tr>
  <% end %>
</table>

app/views/patients/new.html.erb
<body>

<h1> Create a New Patient </h1>
<%= form_for :patient, url: patients_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :phone %><br>
    <%= f.text_area :phone %>
  </p>

  <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>

  <p>
    <%= f.label :dateofbirth %><br>
    <%= f.text_area :dateofbirth %>
  </p>

  <p>
    <%= f.label :status %><br>
    <%= f.text_area :status %>
  </p>

  <p>
    <%= f.label :medication %><br>
    <%= f.text_area :medication %>
  </p>

  <p>
    <%= f.label :emergencycontact %><br>
    <%= f.text_area :emergencycontact %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

</body>

app/views/patients/show.html.erb
<h1> Test </h1>
<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Medical Dosage:</strong>
  <%= @medication.dosage %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @patient.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @patient.address %>
</p>

<p>
  <strong>Date of Birth:</strong>
  <%= @patient.dateofbirth %>
</p>

<p>
  <strong>Cancer Status:</strong>
  <%= @patient.status %>
</p>

<p>
  <strong>Medication:</strong>
  <%= @patient.medication %>
</p>

<p>
  <strong>Emergency Contact:</strong>
  <%= @patient.emergencycontact %>
</p>